version: '3.5'
services:
  autossh:
    container_name: autossh
    image: ubuntu:20.04
    build:
      context: .
      dockerfile: autossh-with-envs.dockerfile
      args:
        SSH_PRV_KEY: 
    environment:
      SSH_PORT: "port_value"
      SSH_TUNNEL: "8080:host_value:80"
      SSH_USER: "user_value"
      SSH_HOST: "host_value"
    network_mode: host
    restart: unless-stopped
